sonar.projectKey=budget-control-fm_budget-control-fm-core
sonar.organization=budget-control-fm
sonar.projectVersion=$(node -p "require('./package.json').version")
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.config.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
