sonar.projectKey=budget-control-fm_budget-control-fm-core
sonar.organization=budget-control-fm
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=test
sonar.test.inclusions=test/**/*.test.ts
sonar.coverage.exclusions=test/**/*.test.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.config.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S2068
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.test.ts