name: CD

run-name: "Version Packages: Publish to npm"

on:
  push:
    branches:
      - main

concurrency:
  group: cd
  cancel-in-progress: false

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'chore: version packages')"

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: 24
          cache: npm
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build

      - name: Smoke-test
        run: npm run smoke

      - name: Publish to npm
        run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
