name: Continuous Delivery

on:
  push:
    branches:
      - main

concurrency:
  group: continuous-delivery
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: Continuous Delivery
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 24
          cache: npm
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Release
        uses: changesets/action@e87c8ed249971350e47fab7515075f44eb134e5b
        with:
          version: npm run version-packages
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
